theme: jekyll-theme-leap-day
encding: utf-8
plugins: 
  - jekyll-github-metadata
source:         .
title:          いっぺーちゃんのメモブログ
description:    作業メモ
show_downloads: false
exclude:        [server.sh, Gemfile, Gemfile.lock]
